
##############################################################
# Terminal Tools Configuration for "Ttools Test"
# Add environments under "Environments"
# Adjust the menu under "Menu" to your needs
##############################################################
Projectname: "ttools-test"
Environments:
  Test:
    Host: "test.title.dk"
    Sshuser: "serverpilot"
    Repodir: "/srv/users/serverpilot/apps/ttools-test"
    #additional settings
    Sshport: ""
    Composerpath: "/srv/users/serverpilot/composer.phar"
    #see here: https://serverpilot.io/community/articles/how-to-use-the-php-cli.html
    PhpPath: "php5.6-sp"
  Demo:
    Host: "demo.title.dk"
    Sshuser: "serverpilot"
    Repodir: "/srv/users/serverpilot/apps/ttools-test"
    #additional settings
    Sshport: ""
    Composerpath: "/srv/users/serverpilot/composer.phar"
    #see here: https://serverpilot.io/community/articles/how-to-use-the-php-cli.html
    PhpPath: "php5.6-sp"
Menu:
  Heading1:
    Title: Local
    Item1:
      Title: Test
      Command: ""
  Heading2:
    Title: Test
    Item1:
      Title: SSH
      Command: "ttools/core/local/ssh.sh Test"
    Item2:
      Title: Deploy
      Command: "ttools/githelpers/local/git-pull-remote.sh Test"
  Heading3:
    Title: Demo
    Item1:
      Title: SSH
      Command: "ttools/core/local/ssh.sh Demo"
    Item2:
      Title: Deploy
      Command: "ttools/githelpers/local/git-pull-remote.sh Demo"
  Heading4:
    Title: Sync
    Item1:
      Title: Local to Test
      Command: "ttools/sitesync-core/local/sync-environments.sh Local Test"
    Item2:
      Title: Test to Local
      Command: "ttools/sitesync-core/local/sync-environments.sh Test Local"
    Item3:
      Title: Test to Demo
      Command: "ttools/sitesync-core/local/sync-environments.sh Test Demo"
    Item4:
      Title: Demo to Test
      Command: "ttools/sitesync-core/local/sync-environments.sh Test Demo"
Sitesync:
  FrameworkModule: 'ttools/sitesync-simple'


