Environments:
  billboardsup:
    Host: "ssh.billboardsup.com"
    Sshuser: "billboardsup.com"
    Repodir: "/home/billboardsup.com/anselm-test"
Menu:
  Heading5:
    Title: billboardsup
    Item1:
      Title: SSH
      Command: "ttools/custom/local/ssh-simple.sh billboardsup"
    Item2:
      Title: Deploy
      Command: "ttools/githelpers/local/git-pull-remote.sh billboardsup"

